apiVersion: v1
kind: Namespace
metadata:
    name: pihole
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:       
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      dnsPolicy: "None"
      dnsConfig: # previously had errors pulling the image needed for the pod, configuring DNS for pod was needed.
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "Europe/Skopje"
            - name: WEBPASSWORD
              value: "12"
            - name: DNSMASQ_LISTENING
              value: "all"
            - name: PIHOLE_DNS_
              value: "8.8.8.8;1.1.1.1"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: dnsmasq-data
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data
        - name: dnsmasq-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-tcp
  namespace: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  namespace: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
