apiVersion: v1
kind: Namespace
metadata:
  name: linkding

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.42.0
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: linkding-web
  namespace: linkding
spec:
  type: LoadBalancer
  selector:
    app: linkding
  ports:
    - name: http
      port: 9091
      targetPort: 9090
      protocol: TCP