apiVersion: v1
kind: Namespace
metadata:
  name: test-app

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: test-app
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-app
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP